sudo: required
services:
  - docker

before_install:
  - docker build -t phantom28/docker-react -f Dockerfile.dev .

script:
  - docker run phantom28/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-east"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbinstalk-eu-east-awwtgaggawg"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"